-- MySQL Script generated by MySQL Workbench
-- Mon Apr 16 14:01:34 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipe` (
  `ID_jogador` INT NOT NULL,
  `nomeEquipe` VARCHAR(45) NULL,
  `nomeJogador` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_jogador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pontuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pontuacao` (
  `ID_pontuacao` INT NOT NULL,
  `pontuacao` DOUBLE NULL,
  `ID_rodada` INT NULL,
  PRIMARY KEY (`ID_pontuacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rodada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rodada` (
  `ID_rodada` INT NOT NULL,
  `pontuacao_ID_pontuacao` INT NOT NULL,
  `pontuacao_ID_pontuacao1` INT NOT NULL,
  `pontuacao_ID_pontuacao2` INT NOT NULL,
  PRIMARY KEY (`ID_rodada`, `pontuacao_ID_pontuacao`, `pontuacao_ID_pontuacao1`),
  INDEX `fk_rodada_pontuacao1_idx` (`pontuacao_ID_pontuacao2` ASC),
  CONSTRAINT `fk_rodada_pontuacao1`
    FOREIGN KEY (`pontuacao_ID_pontuacao2`)
    REFERENCES `mydb`.`pontuacao` (`ID_pontuacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rodada_has_equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rodada_has_equipe` (
  `rodada_ID_rodada` INT NOT NULL,
  `rodada_pontuacao_ID_pontuacao` INT NOT NULL,
  `equipe_ID_jogador` INT NOT NULL,
  PRIMARY KEY (`rodada_ID_rodada`, `rodada_pontuacao_ID_pontuacao`, `equipe_ID_jogador`),
  INDEX `fk_rodada_has_equipe_equipe1_idx` (`equipe_ID_jogador` ASC),
  INDEX `fk_rodada_has_equipe_rodada1_idx` (`rodada_ID_rodada` ASC, `rodada_pontuacao_ID_pontuacao` ASC),
  CONSTRAINT `fk_rodada_has_equipe_rodada1`
    FOREIGN KEY (`rodada_ID_rodada` , `rodada_pontuacao_ID_pontuacao`)
    REFERENCES `mydb`.`rodada` (`ID_rodada` , `pontuacao_ID_pontuacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rodada_has_equipe_equipe1`
    FOREIGN KEY (`equipe_ID_jogador`)
    REFERENCES `mydb`.`equipe` (`ID_jogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
