/*ALTER TABLE IF EXISTS PONTUACAO DROP FOREIGN KEY ID_PONTUACAO;*/

DROP TABLE IF EXISTS EQUIPE;
CREATE TABLE IF NOT EXISTS EQUIPE (
    ID_JOGADOR INTEGER NOT NULL AUTO_INCREMENT,
    NOME_EQUIPE VARCHAR(50) NOT NULL,
    NOME_JOGADOR VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_JOGADOR)
);

DROP TABLE IF EXISTS RODADA;
CREATE TABLE IF NOT EXISTS RODADA (
    ID_RODADA INTEGER NOT NULL AUTO_INCREMENT,
    FOTO_PONTUACAO VARCHAR(200),
    PRIMARY KEY (ID_RODADA)
);

DROP TABLE IF EXISTS PONTUACAO;
CREATE TABLE IF NOT EXISTS PONTUACAO (
    ID_PONTUACAO INTEGER NOT NULL AUTO_INCREMENT,
    ID_JOGADOR INTEGER NOT NULL,
    ID_RODADA INTEGER NOT NULL,
    TOTAL_PONTOS DECIMAL(10, 2),
    PRIMARY KEY (ID_PONTUACAO),
    FOREIGN KEY (ID_JOGADOR)
        REFERENCES EQUIPE(ID_JOGADOR)
        ON DELETE CASCADE,
    FOREIGN KEY  (ID_RODADA)
        REFERENCES RODADA(ID_RODADA)
);