INSERT INTO EQUIPE(NOME_EQUIPE, NOME_JOGADOR) VALUES(,);

INSERT INTO RODADA(FOTO_PONTUACAO) VALUES('FOTO_RODADA_1.JPG');

INSERT INTO PONTUACAO(ID_JOGADOR, ID_RODADA, TOTAL_PONTOS) VALUES(1, 1, 75.86);
INSERT INTO PONTUACAO(ID_JOGADOR, ID_RODADA, TOTAL_PONTOS) VALUES(2, 1, 95.87);
INSERT INTO PONTUACAO(ID_JOGADOR, ID_RODADA, TOTAL_PONTOS) VALUES(3, 1, 84.57);