INSERT INTO EQUIPE(NOME_EQUIPE, NOME_JOGADOR) VALUES(,);

INSERT INTO EQUIPE(NOME_EQUIPE, NOME_JOGADOR) VALUES('Americano F & E','Raphael');
INSERT INTO EQUIPE(NOME_EQUIPE, NOME_JOGADOR) VALUES('Glorioso Cartoleiro','Marcel');
INSERT INTO EQUIPE(NOME_EQUIPE, NOME_JOGADOR) VALUES('Status Nove FC','Valdir');

INSERT INTO RODADA(FOTO_PONTUACAO) VALUES('FOTO_RODADA_1.JPG');

