SELECT RODADA.ID_RODADA, NOME_EQUIPE, NOME_JOGADOR, TOTAL_PONTOS FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA
    ORDER BY TOTAL_PONTOS DESC;

/* criar um join para ordenar pela soma de pontuacao*/
SELECT NOME_JOGADOR, NOME_EQUIPE FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA
    ORDER BY TOTAL_PONTOS DESC;


    /*join de tudo com redundancias*/
SELECT * FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA;

/* Select do total de pontos*/

SELECT TOTAL_PONTOS FROM PONTUACAO 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA
    GROUP BY PONTUACAO.ID_RODADA;

/*  */
SELECT EQUIPE.ID_JOGADOR, PONTUACAO.ID_PONTUACAO FROM EQUIPE JOIN PONTUACAO ON EQUIPE.ID_JOGADOR = PONTUACAO.ID_JOGADOR ORDER BY PONTUACAO.ID_JOGADOR;


-- SELECT 
-- a.nid, a.stock, sum(b.qty)
-- FROM 
-- uc_product_stock a INNER JOIN uc_order_products b ON a.nid = b.nid
-- group by 
-- a.nid, a.stock

-- SELECT PONTUACAO.ID_JOGADOR, EQUIPE.ID_JOGADOR, SUM(PONTUACAO.TOTAL_PONTOS) FROM PONTUACAO INNER JOIN PONTUACAO.ID_JOGADOR = EQUIPE.ID_JOGADOR GROUP BY PONTUACAO.ID_JOGADOR, EQUIPE.ID_JOGADOR;