SELECT RODADA.ID_RODADA, NOME_EQUIPE, NOME_JOGADOR, TOTAL_PONTOS FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA
    ORDER BY TOTAL_PONTOS DESC;

/* criar um join para ordenar pela soma de pontuacao*/
SELECT NOME_JOGADOR, NOME_EQUIPE FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA
    ORDER BY TOTAL_PONTOS DESC;


    /*join de tudo com redundancias*/
SELECT * FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA;