SELECT RODADA.ID_RODADA, NOME_EQUIPE, NOME_JOGADOR, TOTAL_PONTOS FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA
    ORDER BY TOTAL_PONTOS DESC;

/* criar um join para ordenar pela soma de pontuacao*/
SELECT NOME_JOGADOR, NOME_EQUIPE FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA
    ORDER BY TOTAL_PONTOS DESC;


    /*join de tudo com redundancias*/
SELECT * FROM EQUIPE 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA;

/* Select do total de pontos*/

SELECT TOTAL_PONTOS FROM PONTUACAO 
    INNER JOIN PONTUACAO ON EQUIPE.ID_JOGADOR =  PONTUACAO.ID_JOGADOR 
    INNER JOIN RODADA ON PONTUACAO.ID_RODADA = RODADA.ID_RODADA
    GROUP BY PONTUACAO.ID_RODADA;

/*  */
SELECT EQUIPE.ID_JOGADOR, PONTUACAO.ID_PONTUACAO FROM EQUIPE JOIN PONTUACAO ON EQUIPE.ID_JOGADOR = PONTUACAO.ID_JOGADOR ORDER BY PONTUACAO.ID_JOGADOR;

SELECT 
E.NOME_EQUIPE, sum(P.TOTAL_PONTOS) AS TOTAL
FROM 
EQUIPE E INNER JOIN PONTUACAO P ON E.ID_JOGADOR = P.ID_JOGADOR
INNER JOIN RODADA R ON R.ID_RODADA = P.ID_RODADA
GROUP BY  
E.NOME_EQUIPE;




-- SELECT 
-- a.nid, a.stock, sum(b.qty)
-- FROM 
-- uc_product_stock a INNER JOIN uc_order_products b ON a.nid = b.nid
-- group by 
-- a.nid, a.stock

-- SELECT PONTUACAO.ID_JOGADOR, EQUIPE.ID_JOGADOR, SUM(PONTUACAO.TOTAL_PONTOS) FROM PONTUACAO INNER JOIN PONTUACAO.ID_JOGADOR = EQUIPE.ID_JOGADOR GROUP BY PONTUACAO.ID_JOGADOR, EQUIPE.ID_JOGADOR;

-- SELECT 
-- a.nid, a.stock, sum(b.qty)
-- FROM 
-- uc_product_stock a INNER JOIN uc_order_products b ON a.nid = b.nid
-- group by 
-- a.nid, a.stock
-- 
-- 
-- ANOTAÇÕES


-- nid stock   qty
-- 11  256     4
-- 11  256     1
-- 11  256     4
-- 11  256     1
-- 11  256     1
-- 10  746     1
-- 10  746     2
-- 10  746     1

--  nid    stock   qty
--  11     256     11
--  10     746     4

--  SELECT f.TradeID, f.PricingSecurityID, s.TotalQuantity
--   FROM FollowingTableStructure AS f
--   JOIN (SELECT PricingSecurityID, SUM(Quantity) AS TotalQuantity
--           FROM FollowingTableStructure
--          GROUP BY PricingSecurityId
--        ) AS s ON f.PricingSecurityID = s.PricingSecurityID